### ISSUE TITLE
Flesh out ///delta indication ??? with tone()?

### ISSUE THREAD

**Issue by drf5n** [Dreamy16101976/foxyPIv1#1]
This bit of code plans for indicating differences in pulse length:

https://github.com/Dreamy16101976/foxyPIv1/blob/master/FoxyPIv1.ino#L212

The full code looks like it induces a pulse, and counts how long it takes the decay to cross a threshold, and alarms if the length of time is longer than the zero+PROTECT count, then beeps a constant tone.  

Maybe one could map the delta indication into the pitch of a tone?  Instead of:

    analogWrite(beepPin, BEEP_ON)

Maybe:

    tone(beepPin, map(delta,1,100,1000,2000));

To do material discrimination, it seems like it would be necessary to detect more than the threshold-crossing timing.  Maybe timing a couple more thresholds would be possible

Circuit wise, I wonder if you could add a quad comparator like an $0.90 NJM2901 to pick off when the curve first falls below the diode clamp, to 3/4, 1/2, and 1/4 of the diode clamp voltage to give more data on the shape of the the decay curve for discrimination.

(I found this code while looking for pulse induction after seeing the circuit and DSP discussion at https://www.lammertbies.nl/electronics/pi-metal-detector )

**Comment by Dreamy16101976** [comment]
Hello!
This is the first (v1), earliest and very outdated version of my metal detector software. It is laid out just as a keepsake. Therefore, it is hardly worth discussing any technical solutions in this particular version.
Best regards, Alexey

**Comment by drf5n** [comment]
This version of your metal detection software looks like one of the more interesting code examples for pulse induction metal detectors for Arduino.

Is the test and training data in https://github.com/Dreamy16101976/nn4md from a later version of your detector software?
